### PR TITLE
Add assigning yourself roles via emotes

### PR DESCRIPTION
**Pull request by 1whatleytay**
This PR lets you create special messages, where when people react to them they get assigned special roles. The only way to do this right now is by editing the config file.

They're called `reactors` now. :O

### CODE REVIEW

**Review by mk5med — CHANGES_REQUESTED** [review]
Thanks Taylor, this looks great! One change is to add some comments to the `modifyRole` method and the declarations of `Emote` and `EmoteDescription`.

In the future, the primary pull request message should, at minimum, provide a general overview of what changes the PR brings into the code-base without having to look into the list of changed-files.

**Comment by 1whatleytay** [comment]
Hey Viktor!

I don't mind making comments.

The reason I kept it empty
 - Everyone in the dev team was there while we extensively talked about it.
 - Most of the dev team was there while I was actually creating it.
 - Its due ASAP

Thanks :D

**Review by mk5med — APPROVED** [review]
Thanks for adding the changes!

**Comment by 1whatleytay** [comment]
👍

**Pull request merged**
